application: khan-report
version: 1
runtime: python
api_version: 1

handlers:
- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: gae_mini_profiler/main.py

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: .*
  script: main.py

builtins:
- deferred: on
